# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9d78a953f22e8407c0bd6d6fdeaa982879a8d5ffdd99e2eaf2c503fe33c949ecc11d869f983005567c36987e55009f9d895741a8be5ba6a1f03b6910d3f5a720

test:
  secret_key_base: 6639094e3d2c5dbb6a2e3658b2a608601ee8455f1c605b69fa450c245b99bcf8f248773e6ec508a5a4c0b27c1dee130c92e8216ce804ee2e1aba7f2f1fe361c4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
